api/urls.py
from django.urls import include, path
from rest_framework import routers
from api.views import BookmarkViewSet, SubscriptionViewSet



router = routers.DefaultRouter()
router.register(r'bookmarks', BookmarkViewSet)
router.register(r'subscriptions', SubscriptionViewSet)

urlpatterns = [
    path('', include(router.urls))
]

rss2newsletters/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feedaggregator.urls')),
    path('', include('users.urls')),
    path('api/', include('api.urls')),
]

users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from users.views import RegisterCreateView, LoginView, GuestLoginRedirectView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
  path('register/', RegisterCreateView.as_view(), name='register'),
  path('login/', LoginView.as_view(), name='login'),
  path('logout', auth_views.LogoutView.as_view(), name='logout'),
  path('guest_login/', GuestLoginRedirectView.as_view(), name='guest_login'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.utils.translation import gettext_lazy


class SubscriberManager(BaseUserManager):
  def create_user(self, email, first_name, second_name, password, **others):
    if not email:
      raise ValueError(gettext_lazy("You must provide an email address"))

    email = self.normalize_email(email)
    user = self.model(email=email, first_name=first_name, second_name=second_name, **others)
    user.set_password(password)
    user.save()
    return user
  
  def create_superuser(self, email, first_name, second_name, password, **others):
    others.setdefault("is_staff", True)
    others.setdefault("is_superuser", True)
    others.setdefault("is_active", True)

    if others.get("is_staff") is not True:
      raise ValueError("Superuser must be staff")
    if others.get("is_superuser") is not True:
      raise ValueError("Superuser must be superuser")
    return self.create_user(email, first_name, second_name, password, **others)


class Subscriber(AbstractBaseUser, PermissionsMixin):
  email = models.EmailField(gettext_lazy('email address'), unique=True)
  first_name = models.CharField(max_length=50, blank=False)
  second_name = models.CharField(max_length=50, blank=False)
# Trying to follow the existing Django flags
  is_staff = models.BooleanField(default=False)
  is_active = models.BooleanField(default=True)
  
  objects = SubscriberManager()

  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = ['first_name', 'second_name']

  def __str__(self):
    return f"{self.first_name} {self.second_name}"

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from users.models import Subscriber

class NewSubscriberForm(UserCreationForm):
  class Meta:
    model = Subscriber
    fields = ['email', 'first_name', 'second_name', 'password1', 'password2'] 

users/views.py
from django.views import generic
from django.views.generic.base import RedirectView
from users.forms import NewSubscriberForm
from django.contrib.auth import views as auth_views
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy

class RegisterCreateView(generic.CreateView):
  form_class = NewSubscriberForm
  template_name = 'users/register.html'
  success_url = reverse_lazy('feedaggregator:add_feed')

  def form_valid(self, form):
    valid = super().form_valid(form)
    email = form.cleaned_data.get('email')
    password = form.cleaned_data.get('password1')
    registered_user = authenticate(email=email, password=password)
    login(self.request, registered_user)
    return valid

class LoginView(auth_views.LoginView):
  template_name = 'users/login.html'
  redirect_authenticated_user = True

class GuestLoginRedirectView(RedirectView):
  pattern_name = 'feedaggregator:discover_feeds'

  def get_redirect_url(self, *args, **kwargs):
    guest_user = authenticate(self.request, email="guest@gmail.com", password="Guestpassword123*")
    login(self.request, guest_user)
    return super().get_redirect_url(*args, **kwargs)

users/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="{% static 'feedaggregator/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
  <link href="{% static 'feedaggregator/css/sb-admin-2.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 
</head>
<body class="bg-gradient-primary">
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
<!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}
{% block title %}ScrubStack: Login{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome to ScrubStack!</h1>
                                    </div>
                                    <form class="user" method="POST">
                                        {% csrf_token %}
                                        {{ form|crispy }}
                                    <div class="text-center">
                                        <button type="submit" class="btn btn-primary btn-user btn-block">Login</button>
                                    </div>
                                    </form>
                                    <hr>
                                    
                                    <div class="text-center">
                                        <a class="small" href="{% url 'users:register' %}">Create an Account!</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'users:guest_login' %}">Click Here if Guest (or Recruiter)</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
{% endblock %}

users/templates/users/logout.html
<head>
  <title>Logout</title>
</head>
<h1>You are logged out!</h1>

users/templates/users/register.html
{% extends 'users/base.html' %}
{% block title %}ScrubStack: Register{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                            </div>
                            <form method="POST" class="user">
                               {% csrf_token %}
                               {{ form|crispy }} 
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary btn-user btn-block">Create Account!</button>
                                </div>
                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small" href="{% url 'users:login' %}">Already have an account? Login!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

   {% endblock %} 