api/urls.py
from django.urls import include, path
from rest_framework import routers
from api.views import BookmarkViewSet, SubscriptionViewSet



router = routers.DefaultRouter()
router.register(r'bookmarks', BookmarkViewSet)
router.register(r'subscriptions', SubscriptionViewSet)

urlpatterns = [
    path('', include(router.urls))
]

feedaggregator/urls.py
from django.urls import path, include
from feedaggregator.views import *

app_name = 'feedaggregator'

urlpatterns = [
  path('', FeedDiscoverView.as_view(), name='home_view'),
  path('add/', FeedFormView.as_view(), name='add_feed'),
  path('discover/', FeedDiscoverView.as_view(), name='discover_feeds'),
  path('view/', FeedSubscriptionView.as_view(), name="view_feeds"),
  path('entries/<feed_pk>', EntryListView.as_view(), name='entry_list'),
  path('entry/<pk>', EntryDetailView.as_view(), name='entry_detail'),
  path('bookmarks/', EntrySavedView.as_view(), name='bookmarks'),
]

rss2newsletters/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feedaggregator.urls')),
    path('', include('users.urls')),
    path('api/', include('api.urls')),
]

users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from users.views import RegisterCreateView, LoginView, GuestLoginRedirectView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
  path('register/', RegisterCreateView.as_view(), name='register'),
  path('login/', LoginView.as_view(), name='login'),
  path('logout', auth_views.LogoutView.as_view(), name='logout'),
  path('guest_login/', GuestLoginRedirectView.as_view(), name='guest_login'),
]

feedaggregator/models.py
from ast import parse
from django.db import models
from users.models import Subscriber
import feedparser
from datetime import datetime
import pytz
from time import mktime, struct_time
from typing import List
import html


class Category(models.Model):
  title = models.CharField(max_length=50, null=False)

class Feed(models.Model):
  title = models.CharField(max_length=150, blank=True, null=True)
  url = models.URLField(max_length=150, blank=False, unique=True, verbose_name="URL")
  category = models.ManyToManyField(Category, related_name='feeds')
  feed_encoding = models.CharField(max_length=150, blank=True, null=True)
  last_sent = models.DateTimeField(blank=True, null=True)
  subscribers = models.ManyToManyField(Subscriber, through='Subscription', related_name="subscriptions")
  content_key = models.CharField(max_length=25, default="invalid")
  # Checks if RSS entries are sorted most recent first (i.e. True)
  sorted_normal = models.BooleanField(default=True)
  num_subscribers = models.IntegerField(default=0)

  class Meta:
    # FIXME do we need to do it this way
    ordering = ['-num_subscribers']
  
  def __str__(self) -> str:
    if self.title:
      return self.title
    return ""
  
  def generate_entry(self, raw_entry: object) -> 'Entry':
    '''
    Create Entry object given raw entry from parsed feed
    '''
    # TODO create Mail object and add to newsletter_emailer
    # Get the parsed feeds' entries
    new_entry = Entry(
      feed=self,
    )
    if self.content_key == "content":
      new_entry.body = html.unescape(raw_entry["content"][0]["value"])
      new_entry.published_date = self.st_to_dt(raw_entry['published_parsed'])
      new_entry.title = raw_entry["title"]
      new_entry.author = raw_entry["author"]
    elif self.content_key == "summary":
      new_entry.body = html.unescape(raw_entry["summary"])
      new_entry.published_date = self.st_to_dt(raw_entry['published_parsed'])
      new_entry.title = raw_entry["title"]
      new_entry.author = raw_entry["author"]
    return new_entry

  def st_to_dt(self, st: struct_time) -> datetime:
    # Generate datetime object from passed time struct
    # FIXME tz=pytz.utc does not work for some reason
    rel_datetime = datetime.fromtimestamp(mktime(st), tz=pytz.utc)
    return datetime.fromtimestamp(mktime(st), tz=pytz.utc)

  def filter_entries(self, entries_since_date: datetime) -> List[object]:
    '''
    Return all of the feed's entries since specified date

    :param entries_since_date: datetime object that represents the cutoff date for entries
    
    :return: list of entries published since specified date
    '''
    parsed_feed = feedparser.parse(self.url)
    return [x for x in parsed_feed['entries'] \
      if self.st_to_dt(x['published_parsed']) > entries_since_date]


  def save(self, *args, **kwargs):
    # Only want to set title if new object
    if not self.pk:
      # Get the feed's title and check its structure
      # Some have article body text in "content" tag; other's in "description"/"summary"
      parsed_feed = feedparser.parse(self.url) 
      self.title = parsed_feed.feed.title
      if "entries" in parsed_feed and len(parsed_feed["entries"]) > 0:
        if "content" in parsed_feed["entries"][0]:
          self.content_key = "content"
        elif "summary" in parsed_feed["entries"][0]:
          self.content_key = "summary"
        # Check if entries are sorted normally
        # Using a try-except to account for cases where we don't have
        try:
          first_entry_date = self.st_to_dt(parsed_feed["entries"][0]["published_parsed"])
          second_entry_date = self.st_to_dt(parsed_feed["entries"][1]["published_parsed"])
          if first_entry_date < second_entry_date:
            # If they aren't mark the feed as such
            self.sorted_normal = False
        except:
          self.sorted_normal = True
    super(Feed, self).save(*args, **kwargs)
  


class Entry(models.Model):
  feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
  author = models.CharField(max_length=100, default="", blank=True)
  published_date = models.DateTimeField(null=True, default=None)
  title = models.CharField(max_length=254)
  body = models.TextField()
  sent = models.BooleanField(default=False)
  saved_by = models.ManyToManyField(Subscriber, related_name='saved_entries', through='Bookmark')
  
  class Meta:
    ordering = ['-pk']
    verbose_name_plural = "entries"
    
class Subscription(models.Model):
  user = models.ForeignKey(Subscriber, on_delete=models.CASCADE)
  feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
  date_subscribed = models.DateTimeField(auto_now_add=True)

  def __str__(self) -> str:
    return self.feed.title

  class Meta:
    ordering = ['date_subscribed']

class Bookmark(models.Model):
  entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
  subscriber = models.ForeignKey(Subscriber, on_delete=models.CASCADE)
  saved_time = models.DateTimeField(auto_now_add=True)

  class Meta:
    ordering = ['-saved_time']
  
  def __str__(self) -> str:
    return f'{self.entry.title} - {self.subscriber.email}'

feedaggregator/forms.py
from django import forms
from django.core.exceptions import ValidationError
from feedaggregator.models import Feed 
from typing import Optional
import feedparser

class FeedForm(forms.ModelForm):
  class Meta:
    model = Feed 
    fields = ['url']
    widgets = {
      'url': forms.TextInput,
    }
  
  def clean_url(self) -> Optional[str]:
    '''
    Check that provided URL is a valid RSS feed
    '''
    clean_data = self.cleaned_data.get('url')
    feed_data = feedparser.parse(clean_data)
    if feed_data.bozo:
      raise ValidationError("Please enter valid RSS feed.")
    return clean_data

feedaggregator/views.py
from ast import Sub
from django.views import generic
from django.db.models import F, QuerySet
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from feedaggregator.forms import FeedForm
from django.urls import reverse_lazy
from feedaggregator.models import Feed, Subscription, Entry, Bookmark
from users.models import Subscriber
from datetime import datetime, timezone
from django.shortcuts import redirect

# Why does LoginRequiredMixin have to go before CreateView?
# TODO add Entry view!!!
class FeedFormView(LoginRequiredMixin, generic.CreateView):
  template_name = "feedaggregator/add.html"
  form_class = FeedForm
  # FIXME why is lazy necessary?
  success_url = reverse_lazy('feedaggregator:discover_feeds')

  def get(self, *args, **kwargs) -> HttpResponse:
    # FIXME If we're doing this, maybe we don't need a LoginRequiredMixin
    if not self.request.user.is_superuser:
      return redirect(reverse_lazy('feedaggregator:discover_feeds'))
    return super(FeedFormView, self).get(*args, **kwargs)

  def get_context_data(self, **kwargs) -> object:
    context = super().get_context_data(**kwargs)
    context['user_first_name'] = self.request.user.first_name
    return context

class FeedDiscoverView(LoginRequiredMixin, generic.ListView):
  template_name = "feedaggregator/discover.html"
  context_object_name = "feeds"
  queryset = Feed.objects.all()
  paginate_by = 6 

  def get_context_data(self, **kwargs) -> object:
    context = super(FeedDiscoverView, self).get_context_data(**kwargs)
    context["user_subscriptions"] = self.request.user.subscriptions.all()
    return context

class FeedSubscriptionView(LoginRequiredMixin, generic.ListView):
  template_name = "feedaggregator/subscriptions.html"
  context_object_name = "subscriptions"

  def get_queryset(self) -> QuerySet[Subscription]:
    return Subscription.objects.filter(user=self.request.user)

class EntrySavedView(LoginRequiredMixin, generic.ListView):
  context_object_name = "saved_entries"
  template_name = "feedaggregator/saved_entries.html"
  paginate_by = 10 
  
  def get_queryset(self) -> QuerySet[Bookmark]:
    return Bookmark.objects.filter(subscriber=self.request.user)

class EntryListView(LoginRequiredMixin, generic.ListView):
  model = Entry
  template_name = "feedaggregator/entry_list.html"
  context_object_name = "entries"
  ordering = ['-pk']
  paginate_by = 10 

  def get_queryset(self) -> QuerySet[Entry]:
    queryset = Entry.objects.filter(feed__id=self.kwargs['feed_pk'])
    return queryset

  def get_context_data(self, **kwargs) -> object:
    context = super().get_context_data(**kwargs)
    # FIXME non-existent feed guarding
    context['feed_title'] = Feed.objects.get(id=self.kwargs['feed_pk']).title
    return context


class EntryDetailView(LoginRequiredMixin, generic.DetailView):
  model = Entry
  template_name = "feedaggregator/entry_detail.html"
  context_object_name = "entry"

  def get_context_data(self, **kwargs) -> object:
    context = super().get_context_data(**kwargs)
    bm = Bookmark.objects.filter(subscriber=self.request.user, entry=context["entry"])
    context["user_did_bookmark"] = True if bm.count() else False
    context['bookmark_id'] = bm.first().id if bm.count() else ""
    return context

feedaggregator/templates/feedaggregator/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>


    <!-- Custom fonts for this template-->
    <link href="{% static 'feedaggregator/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'feedaggregator/css/sb-admin-2.css' %}" rel="stylesheet">


</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

    {% block sidebar %}
    {% endblock %}  

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

              {% block topbar %}
              
              {% endblock %}
                

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    
                {% block content %}
                {% endblock %}

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; George Tims 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'feedaggregator/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'feedaggregator/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'feedaggregator/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'feedaggregator/js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'feedaggregator/vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'feedaggregator/js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'feedaggregator/js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>

feedaggregator/templates/feedaggregator/partials/pagination.html
{% if page_obj.paginator.num_pages > 1 and page_obj.paginator.num_pages < 10%}
<div class="row justify-content-center">
<div class="col">
<nav aria-label="discover navigation">
  <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
         <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
      {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
      {% endif %}
      {% for page_num in page_obj.paginator.page_range %}
        <li class="page-item {% if page_obj.number == page_num %}active{% endif %}"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
      {% endif %}
</ul>
</nav>
</div>
</div>
{% elif page_obj.paginator.num_pages > 10 %}
<div class="row justify-content-center">
<div class="col">
<nav aria-label="discover navigation">
  <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
         <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
      {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
      {% endif %}
      <li class="page-item {% if page_obj.number == 1 %}active{% endif %}"><a class="page-link" href="?page=1">1</a></li>
      <li class="page-item {% if page_obj.number == 2 %}active{% endif %}"><a class="page-link" href="?page=2">2</a></li>
      {% if page_obj.number > 3 %}
      <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
      {% endif %}
      {% if page_obj.number > 2 and page_obj.number < page_obj.paginator.num_pages|add:"-1" %}
      <li class="page-item active"><a class="page-link">{{ page_obj.number }}</a></li>
      {% endif %}
      {% if page_obj.number < page_obj.paginator.num_pages|add:'-2' %} 
      <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
      {% endif %}
      <li class="page-item {% if page_obj.number == page_obj.paginator.num_pages|add:'-1' %}active{% endif %}"><a class="page-link" href="?page={{ page_obj.paginator.num_pages|add:'-1' }}">{{ page_obj.paginator.num_pages|add:'-1' }}</a></li>
      <li class="page-item {% if page_obj.number == page_obj.paginator.num_pages %}active{% endif %}"><a class="page-link" href=?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
      {% endif %}
</ul>
</nav>
</div>
</div>
{% endif %}

feedaggregator/templates/feedaggregator/partials/sidebar.html
<!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion toggled" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'feedaggregator:discover_feeds' %}">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-book"></i>
                </div>
                <div class="sidebar-brand-text mx-3">ScrubStack</div>
            </a>
            <!-- Nav Item - Discover -->
            <li class="nav-item {% if selected == 'discover' %}active{% endif %}">
                <a class="nav-link" href="{% url 'feedaggregator:discover_feeds' %}">
                    <i class="fas fa-search"></i>
                    <span>Discover</span></a>
            </li>

            <!-- Nav Item - Subscription -->
            <li class="nav-item {% if selected == 'view' %}active{% endif %}">
                <a class="nav-link" href="{% url 'feedaggregator:view_feeds' %}">
                    <i class="fas fa-inbox"></i>
                    <span>Subscriptions</span></a>
            </li>
            <li class="nav-item {% if selected == 'bookmarks' %}active{% endif %}">
                <a class="nav-link" href="{% url 'feedaggregator:bookmarks' %}">
                    <i class="fas fa-bookmark"></i>
                    <span>Bookmarks</span></a>
            </li>
            <!-- Divider -->
            


        </ul>
        <!-- End of Sidebar -->

feedaggregator/templates/feedaggregator/partials/topbar.html
{% load static %}
<!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <div class="h3 inline-block mr-auto ml-md-3 my-2 my-md-0 mw-100">
                        {{ topbar_title }}
                    </div>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">


                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img class="img-profile rounded-circle"
                                    src="{% static 'feedaggregator/img/undraw_profile.svg' %}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="{% url 'feedaggregator:bookmarks' %}">
                                    <i class="fas fa-bookmark fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Bookmarks
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->