api/urls.py
from django.urls import include, path
from rest_framework import routers
from api.views import BookmarkViewSet, SubscriptionViewSet



router = routers.DefaultRouter()
router.register(r'bookmarks', BookmarkViewSet)
router.register(r'subscriptions', SubscriptionViewSet)

urlpatterns = [
    path('', include(router.urls))
]

feedaggregator/urls.py
from django.urls import path, include
from feedaggregator.views import *

app_name = 'feedaggregator'

urlpatterns = [
  path('', FeedDiscoverView.as_view(), name='home_view'),
  path('add/', FeedFormView.as_view(), name='add_feed'),
  path('discover/', FeedDiscoverView.as_view(), name='discover_feeds'),
  path('view/', FeedSubscriptionView.as_view(), name="view_feeds"),
  path('entries/<feed_pk>', EntryListView.as_view(), name='entry_list'),
  path('entry/<pk>', EntryDetailView.as_view(), name='entry_detail'),
  path('bookmarks/', EntrySavedView.as_view(), name='bookmarks'),
]

rss2newsletters/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('feedaggregator.urls')),
    path('', include('users.urls')),
    path('api/', include('api.urls')),
]

feedaggregator/models.py
from ast import parse
from django.db import models
from users.models import Subscriber
import feedparser
from datetime import datetime
import pytz
from time import mktime, struct_time
from typing import List
import html


class Category(models.Model):
  title = models.CharField(max_length=50, null=False)

class Feed(models.Model):
  title = models.CharField(max_length=150, blank=True, null=True)
  url = models.URLField(max_length=150, blank=False, unique=True, verbose_name="URL")
  category = models.ManyToManyField(Category, related_name='feeds')
  feed_encoding = models.CharField(max_length=150, blank=True, null=True)
  last_sent = models.DateTimeField(blank=True, null=True)
  subscribers = models.ManyToManyField(Subscriber, through='Subscription', related_name="subscriptions")
  content_key = models.CharField(max_length=25, default="invalid")
  # Checks if RSS entries are sorted most recent first (i.e. True)
  sorted_normal = models.BooleanField(default=True)
  num_subscribers = models.IntegerField(default=0)

  class Meta:
    # FIXME do we need to do it this way
    ordering = ['-num_subscribers']
  
  def __str__(self) -> str:
    if self.title:
      return self.title
    return ""
  
  def generate_entry(self, raw_entry: object) -> 'Entry':
    '''
    Create Entry object given raw entry from parsed feed
    '''
    # TODO create Mail object and add to newsletter_emailer
    # Get the parsed feeds' entries
    new_entry = Entry(
      feed=self,
    )
    if self.content_key == "content":
      new_entry.body = html.unescape(raw_entry["content"][0]["value"])
      new_entry.published_date = self.st_to_dt(raw_entry['published_parsed'])
      new_entry.title = raw_entry["title"]
      new_entry.author = raw_entry["author"]
    elif self.content_key == "summary":
      new_entry.body = html.unescape(raw_entry["summary"])
      new_entry.published_date = self.st_to_dt(raw_entry['published_parsed'])
      new_entry.title = raw_entry["title"]
      new_entry.author = raw_entry["author"]
    return new_entry

  def st_to_dt(self, st: struct_time) -> datetime:
    # Generate datetime object from passed time struct
    # FIXME tz=pytz.utc does not work for some reason
    rel_datetime = datetime.fromtimestamp(mktime(st), tz=pytz.utc)
    return datetime.fromtimestamp(mktime(st), tz=pytz.utc)

  def filter_entries(self, entries_since_date: datetime) -> List[object]:
    '''
    Return all of the feed's entries since specified date

    :param entries_since_date: datetime object that represents the cutoff date for entries
    
    :return: list of entries published since specified date
    '''
    parsed_feed = feedparser.parse(self.url)
    return [x for x in parsed_feed['entries'] \
      if self.st_to_dt(x['published_parsed']) > entries_since_date]


  def save(self, *args, **kwargs):
    # Only want to set title if new object
    if not self.pk:
      # Get the feed's title and check its structure
      # Some have article body text in "content" tag; other's in "description"/"summary"
      parsed_feed = feedparser.parse(self.url) 
      self.title = parsed_feed.feed.title
      if "entries" in parsed_feed and len(parsed_feed["entries"]) > 0:
        if "content" in parsed_feed["entries"][0]:
          self.content_key = "content"
        elif "summary" in parsed_feed["entries"][0]:
          self.content_key = "summary"
        # Check if entries are sorted normally
        # Using a try-except to account for cases where we don't have
        try:
          first_entry_date = self.st_to_dt(parsed_feed["entries"][0]["published_parsed"])
          second_entry_date = self.st_to_dt(parsed_feed["entries"][1]["published_parsed"])
          if first_entry_date < second_entry_date:
            # If they aren't mark the feed as such
            self.sorted_normal = False
        except:
          self.sorted_normal = True
    super(Feed, self).save(*args, **kwargs)
  


class Entry(models.Model):
  feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
  author = models.CharField(max_length=100, default="", blank=True)
  published_date = models.DateTimeField(null=True, default=None)
  title = models.CharField(max_length=254)
  body = models.TextField()
  sent = models.BooleanField(default=False)
  saved_by = models.ManyToManyField(Subscriber, related_name='saved_entries', through='Bookmark')
  
  class Meta:
    ordering = ['-pk']
    verbose_name_plural = "entries"
    
class Subscription(models.Model):
  user = models.ForeignKey(Subscriber, on_delete=models.CASCADE)
  feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
  date_subscribed = models.DateTimeField(auto_now_add=True)

  def __str__(self) -> str:
    return self.feed.title

  class Meta:
    ordering = ['date_subscribed']

class Bookmark(models.Model):
  entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
  subscriber = models.ForeignKey(Subscriber, on_delete=models.CASCADE)
  saved_time = models.DateTimeField(auto_now_add=True)

  class Meta:
    ordering = ['-saved_time']
  
  def __str__(self) -> str:
    return f'{self.entry.title} - {self.subscriber.email}'

feedaggregator/forms.py
from django import forms
from django.core.exceptions import ValidationError
from feedaggregator.models import Feed 
from typing import Optional
import feedparser

class FeedForm(forms.ModelForm):
  class Meta:
    model = Feed 
    fields = ['url']
    widgets = {
      'url': forms.TextInput,
    }
  
  def clean_url(self) -> Optional[str]:
    '''
    Check that provided URL is a valid RSS feed
    '''
    clean_data = self.cleaned_data.get('url')
    feed_data = feedparser.parse(clean_data)
    if feed_data.bozo:
      raise ValidationError("Please enter valid RSS feed.")
    return clean_data

feedaggregator/views.py
from ast import Sub
from django.views import generic
from django.db.models import F, QuerySet
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from feedaggregator.forms import FeedForm
from django.urls import reverse_lazy
from feedaggregator.models import Feed, Subscription, Entry, Bookmark
from users.models import Subscriber
from datetime import datetime, timezone
from django.shortcuts import redirect

# Why does LoginRequiredMixin have to go before CreateView?
# TODO add Entry view!!!
class FeedFormView(LoginRequiredMixin, generic.CreateView):
  template_name = "feedaggregator/add.html"
  form_class = FeedForm
  # FIXME why is lazy necessary?
  success_url = reverse_lazy('feedaggregator:discover_feeds')

  def get(self, *args, **kwargs) -> HttpResponse:
    # FIXME If we're doing this, maybe we don't need a LoginRequiredMixin
    if not self.request.user.is_superuser:
      return redirect(reverse_lazy('feedaggregator:discover_feeds'))
    return super(FeedFormView, self).get(*args, **kwargs)

  def get_context_data(self, **kwargs) -> object:
    context = super().get_context_data(**kwargs)
    context['user_first_name'] = self.request.user.first_name
    return context

class FeedDiscoverView(LoginRequiredMixin, generic.ListView):
  template_name = "feedaggregator/discover.html"
  context_object_name = "feeds"
  queryset = Feed.objects.all()
  paginate_by = 6 

  def get_context_data(self, **kwargs) -> object:
    context = super(FeedDiscoverView, self).get_context_data(**kwargs)
    context["user_subscriptions"] = self.request.user.subscriptions.all()
    return context

class FeedSubscriptionView(LoginRequiredMixin, generic.ListView):
  template_name = "feedaggregator/subscriptions.html"
  context_object_name = "subscriptions"

  def get_queryset(self) -> QuerySet[Subscription]:
    return Subscription.objects.filter(user=self.request.user)

class EntrySavedView(LoginRequiredMixin, generic.ListView):
  context_object_name = "saved_entries"
  template_name = "feedaggregator/saved_entries.html"
  paginate_by = 10 
  
  def get_queryset(self) -> QuerySet[Bookmark]:
    return Bookmark.objects.filter(subscriber=self.request.user)

class EntryListView(LoginRequiredMixin, generic.ListView):
  model = Entry
  template_name = "feedaggregator/entry_list.html"
  context_object_name = "entries"
  ordering = ['-pk']
  paginate_by = 10 

  def get_queryset(self) -> QuerySet[Entry]:
    queryset = Entry.objects.filter(feed__id=self.kwargs['feed_pk'])
    return queryset

  def get_context_data(self, **kwargs) -> object:
    context = super().get_context_data(**kwargs)
    # FIXME non-existent feed guarding
    context['feed_title'] = Feed.objects.get(id=self.kwargs['feed_pk']).title
    return context


class EntryDetailView(LoginRequiredMixin, generic.DetailView):
  model = Entry
  template_name = "feedaggregator/entry_detail.html"
  context_object_name = "entry"

  def get_context_data(self, **kwargs) -> object:
    context = super().get_context_data(**kwargs)
    bm = Bookmark.objects.filter(subscriber=self.request.user, entry=context["entry"])
    context["user_did_bookmark"] = True if bm.count() else False
    context['bookmark_id'] = bm.first().id if bm.count() else ""
    return context

feedaggregator/templates/feedaggregator/add.html
{% extends 'feedaggregator/partials/base.html' %}
{% block title %}Add Feed{% endblock %}
{% block sidebar %}
{% include 'feedaggregator/partials/sidebar.html' with selected='' %}
{% endblock %}
{% block topbar %}
{% include 'feedaggregator/partials/topbar.html' with topbar_title='Add Feed' %}
{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card">
  <div class="card-body">
    <div class="card-title"><h5>Enter Feed URL</h5></div>
      <div class="card-text">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <button class="btn btn-primary" type="submit">Add Feed</button>
        </form>
    </div>
  </div>
</div>
{% endblock %}

feedaggregator/templates/feedaggregator/discover.html
{% extends 'feedaggregator/partials/base.html' %}
{% load feedaggregator_extras %}
{% block title %}Discover Feeds{% endblock %}
{% block sidebar %}
{% include 'feedaggregator/partials/sidebar.html' with selected='discover' %}
{% endblock %}
{% block topbar %}
{% include 'feedaggregator/partials/topbar.html' with topbar_title='Discover' %}
{% endblock %}
{% block content %}
<!-- Page Heading -->
                    <!-- Content Row -->
                    <div class="row">

                        <!-- Earnings (Monthly) Card Example -->
                        <div class="col-xl-12 col-md-12 mb-4">
                            <div class="card shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col">
                                            <div class="mb-0 font-weight-bold text-gray-800">
                                                
                                                {% if feeds %}
                                                <ul class="list-group list-group-flush">
                                                    {% for feed in feeds %}
                                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                                    <a href="{% url 'feedaggregator:entry_list' feed_pk=feed.pk %}">{{ feed }}</a>
                                                    {% if feed in user_subscriptions %}
                                                        <span class="badge badge-danger badge-pill subscribe_btn" id="{{ feed|feedToSubId:user.id }}">-</span> 
                                                    {% else %}
                                                        <span class="badge badge-success badge-pill subscribe_btn" id='{{ feed.pk }}'>+</span>
                                                    {% endif %}
                                                    </li>
                                                    {% endfor %}
                                                </ul>
                                                {% include 'feedaggregator/partials/pagination.html' %}
                                                {% else %}
                                                No feeds yet :(
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <script>

                        function subscribe_feed(e) {
                            var http = new XMLHttpRequest();

                            // FIXME figure out how to do this with URL tag
                            var url = '/api/subscriptions/';
                            var method = "POST";
                            
                            http.open(method, url, true);

                            http.setRequestHeader('Content-Type', 'application/json;charset=UTF-8');
                            http.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
                            
                            http.onreadystatechange = function () {
                                if (http.readyState == 4 && http.status == 201) {
                                    e.target.classList.remove('badge-success');
                                    e.target.classList.add('badge-danger');
                                    e.target.innerHTML = "-";
                                    console.log(http.responseText);
                                    var newEId = JSON.parse(http.responseText)['id'];
                                    e.target.id = newEId;
                                }
                            }

                            http.send(
                                JSON.stringify({
                                    feed: e.target.id,
                                    user: {{ request.user.id }}
                                })
                            );

                        }
                        function unsubscribe_feed(e) {
                            var http = new XMLHttpRequest();
                            // FIXME figure out how to do this with URL tag
                            var url = '/api/subscriptions/' + e.target.id + '/';
                            var method = "DELETE";
                            
                            http.open(method, url, true);

                            http.setRequestHeader('Content-Type', 'application/json;charset=UTF-8');
                            http.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
                            
                            http.onreadystatechange = function () {
                                if (http.readyState == 4 && http.status == 201) {
                                    // FIXME is this right httpstatus given it's a delete?
                                    // Generally it's 204, but this has response content
                                    e.target.classList.remove('badge-danger');
                                    e.target.classList.add('badge-success');
                                    e.target.innerHTML = "+";
                                    // FIXME this is so bad. Need to figure out what's going on here
                                    var fid = JSON.parse(JSON.parse(http.responseText));
                                    e.target.id = fid['feed'];
                                }
                            }

                            http.send(
                                JSON.stringify({
                                    subscription: e.target.id,
                                })
                            )
                        }
                        document.querySelectorAll('.subscribe_btn').forEach((btn) => {
                                btn.addEventListener('click', e => {
                                var buttonType = e.target.innerHTML;
                                if (buttonType === "+") {
                                    subscribe_feed(e);
                                } else {
                                    unsubscribe_feed(e);
                                }
                                })
                            }   
                        );
                    </script>
{% endblock %}

feedaggregator/templates/feedaggregator/entry_list.html
{% extends 'feedaggregator/partials/base.html' %}
{% block title %}{{ feed_title }}{% endblock %}
{% block sidebar %}
{% include 'feedaggregator/partials/sidebar.html' with selected='discover' %}
{% endblock %}
{% block topbar %}
{% include 'feedaggregator/partials/topbar.html' with topbar_title=feed_title %}
{% endblock %}
{% block content %}
<!-- Page Heading -->

                    <!-- Content Row -->
                    <div class="row">

                        <!-- Earnings (Monthly) Card Example -->
                        <div class="col-xl-12 col-md-12 mb-4">
                            <div class="card shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="mb-0 font-weight-bold text-gray-800">
                                                
                                                {% if entries %}
                                                <ul class="list-group list-group-flush">
                                                    {% for entry in entries %}
                                                    <li class="list-group-item">
                                                        <a href="{% url 'feedaggregator:entry_detail' pk=entry.pk %}">{{ entry.title }}</a>
                                                    </li>
                                                    {% endfor %}
                                                </ul>
                                                {% else %}
                                                <!-- need to get rid of weird spacing -->
                                                There are no entries for this feed :(
                                                {% endif %}
                                                {% include 'feedaggregator/partials/pagination.html' %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock %}

feedaggregator/templates/feedaggregator/list.html
<ul>
{% for feed in feeds %}
  <li>{{ feed }}</li>
{% endfor %}
</ul>

feedaggregator/templates/feedaggregator/saved_entries.html
{% extends 'feedaggregator/partials/base.html' %}
{% block title %}Discover Feeds{% endblock %}
{% block sidebar %}
{% include 'feedaggregator/partials/sidebar.html' with selected='bookmarks' %}
{% endblock %}
{% block topbar %}
{% include 'feedaggregator/partials/topbar.html' with topbar_title='Bookmarks' %}
{% endblock %}
{% block content %}
<!-- Page Heading -->
                    <!-- Content Row -->
                    <div class="row">

                        <!-- Earnings (Monthly) Card Example -->
                        <div class="col-xl-12 col-md-12 mb-4">
                            <div class="card shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col">
                                            <div class="h7 mb-0 font-weight-bold text-gray-800">
                                               
                                                {% if saved_entries %}
                                                <ul class="list-group list-group-flush">
                                                {% for bookmark in saved_entries %}
                                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                                <a href="{% url 'feedaggregator:entry_detail' pk=bookmark.entry.pk %}">{{ bookmark.entry.title }}</a><span class="badge badge-danger badge-pill unbookmark_btn" id="{{ bookmark.pk }}|{{bookmark.entry.pk}}">-</span>
                                                </li>
                                                {% endfor %}
                                                </ul>
                                                {% else %}
                                                <!-- need to get rid of weird spacing -->
                                                You have no saved bookmarks!
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
<script>

                        function unbookmark_entry(e) {
                            var http = new XMLHttpRequest();
                            var triggerElement = e.target;
                            var [bookmark_id, entry_id] = triggerElement.id.split("|");
                            // FIXME figure out how to do this with URL tag
                            var url = '/api/bookmarks/' + bookmark_id + '/';
                            var method = "DELETE";
                            
                            http.open(method, url, true);

                            http.setRequestHeader('Content-Type', 'application/json;charset=UTF-8');
                            http.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
                            
                            http.onreadystatechange = function () {
                                if (http.readyState == 4 && http.status == 204) {
                                   console.log(triggerElement.parentElement.parentElement.children.length - 1);
                                   if (triggerElement.parentElement.parentElement.children.length - 1 == 0) {
                                    triggerElement.parentElement.parentElement.innerHTML = "You have no bookmarks!";
                                   } else {
                                    triggerElement.parentElement.parentElement.removeChild(triggerElement.parentElement); 
                                   }
                                }
                            }

                            http.send(
                                JSON.stringify({
                                    entry: entry_id,
                                    subscriber: {{ request.user.id }}
                                })
                            )
                        }

                        document.querySelectorAll('.unbookmark_btn').forEach((btn) => {
                                btn.addEventListener('click', e => {
                                    unbookmark_entry(e);
                                });
                            }   
                        );
                    </script>
{% endblock %}

feedaggregator/templates/feedaggregator/subscriptions.html
{% extends 'feedaggregator/partials/base.html' %}
{% block title %}Discover Feeds{% endblock %}
{% block sidebar %}
{% include 'feedaggregator/partials/sidebar.html' with selected='view' %}
{% endblock %}
{% block topbar %}
{% include 'feedaggregator/partials/topbar.html' with topbar_title='Subscriptions' %}
{% endblock %}
{% block content %}
<!-- Page Heading -->
                    <!-- Content Row -->
                    <div class="row">

                        <!-- Earnings (Monthly) Card Example -->
                        <div class="col-xl-12 col-md-12 mb-4">
                            <div class="card shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="mb-0 font-weight-bold text-gray-800">
                                                
                                                {% if subscriptions %}
                                                <ul class="list-group list-group-flush">
                                                {% for subscription in subscriptions %}
                                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                                    <a href="{% url 'feedaggregator:entry_list' feed_pk=subscription.feed.pk %}">{{ subscription }}</a> <span class="badge badge-danger badge-pill unsubscribe_btn" id="{{ subscription.id }}">-</span>
                                                </li>
                                                {% endfor %}
                                                </ul>
                                                {% else %}
                                                You have no subscriptions. <a href="{% url 'feedaggregator:discover_feeds' %}">Discover some!</a>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <script>

                        function unsubscribe_feed(e) {
                            var http = new XMLHttpRequest();
                            // FIXME figure out how to do this with URL tag
                            var url = '/api/subscriptions/' + e.target.id + '/';
                            var method = "DELETE";
                            
                            http.open(method, url, true);

                            http.setRequestHeader('Content-Type', 'application/json;charset=UTF-8');
                            http.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
                            
                            http.onreadystatechange = function () {
                                if (http.readyState == 4 && http.status == 201) {
                                   var triggerElement = e.target;
                                   console.log(triggerElement.parentElement.parentElement.children.length - 1);
                                   if (triggerElement.parentElement.parentElement.children.length - 1 == 0) {
                                    triggerElement.parentElement.parentElement.innerHTML = "You have no subscriptions. Discover some!";
                                   } else {
                                    triggerElement.parentElement.parentElement.removeChild(e.target.parentElement); 
                                   }
                                }
                            }

                            http.send(
                                JSON.stringify({
                                    subscription: e.target.id,
                                })
                            )
                        }

                        document.querySelectorAll('.unsubscribe_btn').forEach((btn) => {
                                btn.addEventListener('click', e => {
                                    unsubscribe_feed(e);
                                });
                            }   
                        );
                    </script>
{% endblock %}